[images]
  remote_images = ["https://images.unsplash.com/*/*"]

[build]
  command = "npx next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NODE_ENV = "production"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[plugins]]
  package = "@netlify/plugin-nextjs"
